version: '3.9'
services:
  vlp-ic-api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]