version: '3.9'
services:
  detectron-vlp-api:
    build:
      - context: ./detectron_vlp_api
    networks:
      - vlp_service

  vlp-ic-api:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./app:/usr/src/app
      - /mlcv:/mlcv
    networks:
      - vlp_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

networks:
  vlp_service: