version: '3.9'
services:
  detectron-vlp-api:
    build:
      context: ./detectron_vlp_api
    # image: khiemledev/detectron_vlp_api
    volumes:
      - ./detectron_vlp_api/:/workingspace/
    ports:
      - 8083:5055
    networks:
      - vlp_service
    deploy:
      restart_policy:
        condition: on-failure
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  vlp-ic-api:
    build: .
    ports:
      - "8082:80"
    volumes:
      - /usr/src/app/vlp/checkpoints
      - /usr/src/app/vlp/bert
      - ./app:/usr/src/app
      - /mlcv:/mlcv
    networks:
      - vlp_service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

networks:
  vlp_service: